<!DOCTYPE html>
	<html>
		<head>
			<title>Steam Reviews</title>
			<meta> charset="UTF-8">
			<link href="stylesheet.css" rel="stylesheet" type="text/css">
		</head>
	<body>
		<h1>Steam Reviews Data Relationship Model</h1>
		<img src="datadesignproject.svg" />
	<h2>Persona</h2>
		<p>John Gamer is a young professional in the IT world who spends a lot of his limited free time building computer systems and playing games on those systems. He has a reasonable amount of surplus money to spend on games. He doesn't like to waste his time or bandwidth on games that he knows he won't like so finding reliable and upvoted reviews is a good resource for him.</p>
	<h2>Steam Review Use Case</h2>
		<p>To supply user reviews that are generated by actual users/peers of those that are in turn looking to buy games from the Steam service</p>
	</body>
</html>