<!DOCTYPE html>
	<html>
		<head>
			<title>Steam Reviews</title>
			<meta charset="UTF-8">
			<link href="stylesheet.css" rel="stylesheet" type="text/css">
		</head>
	<body>
		<h1>Steam Reviews Data Relationship Model</h1>
		<p>
			<img src="erd.svg" />
		</p>
	<h2>Persona</h2>
		<p>John Gamer is a young professional in the IT world who spends a lot of his limited free time building computer systems and playing games on those systems. He has a reasonable amount of surplus money to spend on games. He doesn't like to waste his time or bandwidth on games that he knows he won't like so finding reliable and upvoted reviews is a good resource for him.</p>
	<h2>Steam Review Use Case</h2>
		<p>To supply user reviews that are generated by actual users/peers of those that are in turn looking to buy games from the Steam service. This is mainly to boost sales buy using existing customers as the sales person, where John Gamer will trust his contemporaries to then spend money on the Steam Store.</p>
		<p>A person will look at steam reviews when a new game comes out in order to decide on whether to buy it or not. User goes to steam because there are plentiful reviews that are thumbs upped or down, marked as funny, and flagged in unhelpful or inappropriate. </p>
	</body>
</html>